version: "3"
services:
  pizza_orders_db:
    image: mongo:7.0.5
    container_name: pizza_orders_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/pizza_orders_db:/data/db
    networks:
      - pizza_network

  pizzas_menu_db:
    image: mongo:7.0.5
    container_name: pizzas_menu_db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/pizza_menu_db:/data/db
    networks:
      - pizza_network

  pizzas_customers_db:
    image: mongo:7.0.5
    container_name: pizzas_customers_db
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/pizza_customers_db:/data/db
    networks:
      - pizza_network

  pizza_customers_api:
    container_name: pizzas_customers_api
    build:
      context: ./pizzas_customers_api
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - pizzas_customers_db
    networks:
      - pizza_network

  pizza_menu_api:
    container_name: pizzas_menu_api
    build:
      context: ./pizzas_menu_api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - pizzas_menu_db
    networks:
      - pizza_network

  app:
    container_name: webapp
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - pizza_network

networks:
  pizza_network:
    driver: bridge
